name       : perl-mime-base64
version    : 3.15
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/MIME-Base64-3.15.tar.gz : 7f863566a6a9cb93eda93beadb77d9aa04b9304d769cea3bb921b9a91b3a1eb9
license    : GPL-2.0
summary    : MIME::Base64 - Encoding and decoding of base64 strings
component  : programming.perl
description: |
    MIME::Base64 - Encoding and decoding of base64 strings
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
